kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: kale-test-cluster-role-binding
  namespace: kubeflow
subjects:
  - kind: ServiceAccount
    name: default
    namespace: kubeflow
roleRef:
  kind: Role
  name: kale-test-cluster-role
  apiGroup: rbac.authorization.k8s.io
